version: '2.2'
services:
 zookeeper:
  image: "zookeeper:3.5"
  container_name: zookeeper-93
  restart: always
  privileged: true
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888
  volumes:
    - "/app/zookeeper/data:/data"
    - "/app/zookeeper/datalog:/datalog"
    - "/app/zookeeper/log:/log"
  environment:
    ZOO_MY_ID: 3
    ZOO_SERVERS: server.1=10.18.4.53:2888:3888;2181 server.2=10.18.4.80:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
