version: '2.2'
services:
 kafka:
  image: "wurstmeister/kafka:2.12-2.3.0"
  container_name: kafka-14
  restart: always
  privileged: true
  ports:
    - "9092:9092"
  environment:
   KAFKA_BROKER_ID: 2
   KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.73.200.14:9092
   KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
   KAFKA_ZOOKEEPER_CONNECT: 10.73.200.14:2181,10.73.200.15:2181,10.73.200.16:2181
   KAFKA_CREATE_TOPICS: "js_eval.requests:100:1:delete --config=retention.ms=60000 --config=segment.bytes=26214400 --config=retention.bytes=104857600,tb_transport.api.requests:3:1:delete --config=retention.ms=60000 --config=segment.bytes=26214400 --config=retention.bytes=104857600"
   KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
   KAFKA_LOG_RETENTION_BYTES: 1073741824
   KAFKA_LOG_SEGMENT_BYTES: 268435456
   KAFKA_LOG_RETENTION_MS: 300000
   KAFKA_LOG_CLEANUP_POLICY: delete
   
   
   10.73.200.14:9092,10.73.200.15:9092,10.73.200.16:9092
   
   
   docker run -d -p 9092:9092 --name kafka-standalone  -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://10.18.4.93:9092  -e KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092 -e KAFKA_ZOOKEEPER_CONNECT=10.18.4.81:2181 wurstmeister/kafka:2.12-2.3.0